### ISSUE TITLE
Crash when creating a multisig account

### ISSUE THREAD

**Issue by thomasoehri** [NemProject/NEMiOSApp#230] opened 2016-06-11 18:19 UTC
I created two new accounts, opened the first account and tried to add the second account as a new signer and the app crashed. It doesn't make a difference when i use older accounts with balance - the app still crashes when i try to add a new signer to the account. I'm using Version 2.0 (38) on an iPhone 6s with iOS 9.3.2.

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by Mehbsl** [comment] 2016-06-11 18:56
I just realized that this issue is a duplicate of #225

**Comment by LyubomirDominik** [comment] 2016-06-13 15:13
Fixed in Version 2 Build 39

**Comment by Mehbsl** [comment] 2016-06-14 14:18
Still doesn't work for me, the app crashes. (build 39)

**Comment by kmiliak** [comment] 2016-06-14 14:34
Issue with adding ONE signer is fixed in version 39. Issue with adding more than one doesn't included to this build.

**Comment by Mehbsl** [comment] 2016-06-14 15:55
If i copy the address of the second account, paste it into the additional signer textfield of the first account and hit add signer the app crashes, i'm not able to add a single signer.

**Comment by LyubomirDominik** [comment] 2016-07-08 09:07
Fixed in Version 2 Build 40

**Comment by jabo38** [comment] 2016-07-15 04:28
not fixed

**Comment by LyubomirDominik** [comment] 2016-07-19 11:29
Remove accounts from address book and reinstall app. And try again.
Account is broken, they was created in old versions or manually

**Comment by jabo38** [comment] 2016-07-25 20:25
removed all accounts from address book.  deleted app.  made new account.  problem is exactly the same.  

pasting an address of an account causes the app to crash.

**Comment by LyubomirDominik** [comment] 2016-07-26 09:22
Fixed in Version 2 Build 42.

Also if you pass address for unknown account (for app) it will show localized error "UNKNOWN_ACCOUNT_ADDRESS" localization exist in app and google doc, but on in localization files provided for us.

**Comment by jabo38** [comment] 2016-07-26 15:07
fixed

**Closed by jabo38** 2016-07-26 15:07 UTC
Labels: bug, help wanted, mustfix, resolved
