### ISSUE TITLE
App crashes when i lose internet connectivity while trying to send a transaction

### ISSUE THREAD

**Issue by thomasoehri** [NemProject/NEMiOSApp#249] opened 2016-06-16 18:45 UTC
When i try to send a transaction from my transaction history and my internet connection gets lost the app will crash as soon as i tap on the amount textfield or the message textfield. (version 2 build 39)

See this video for more infos:
https://youtu.be/AVW_CKQnWlo

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by jabo38** [comment] 2016-06-17 06:56
I couldn't reproduce.  

@LyubomirDominik can you please look into this. In the video he is having a problem for sure.

**Comment by LyubomirDominik** [comment] 2016-07-06 14:16
Fixed in Version 2 Build 40 Was a problem with connection

**Comment by thomasoehri** [comment] 2016-07-15 09:30
Fixed with build 40

**Comment by jabo38** [comment] 2016-07-15 18:57
will close if fixed

**Closed by jabo38** 2016-07-15 18:57 UTC
Labels: bug, mustfix, resolved

**Comment by jabo38** [comment] 2016-08-02 18:22
Bounty paid. Tx hash: a9115b25b3a33e9c3642d57a86fcbadc5e08028e2bf49410a34e17a6e862a77a
