### ISSUE TITLE
Unable to build app with latest xCode. Swift Compiler errors in NemAPI.swift

### ISSUE THREAD

**Issue by merc1305** [NemProject/NEMiOSApp#314] opened 2018-01-18 09:13 UTC
xCode Version 9.2 (9C40b). Same behaviour for building on simulator or real device.

```
/Users/yauhenishauchenka/Desktop/sources/projects/NEMiOSApp/NEMWallet/Application/Networking/NemAPI.swift:19:48: Incorrect argument label in call (have 'url:sampleResponseClosure:method:task:httpHeaderFields:', expected 'url:sampleResponseClosure:method:parameters:httpHeaderFields:')
/Users/yauhenishauchenka/Desktop/sources/projects/NEMiOSApp/NEMWallet/Application/Networking/NemAPI.swift:36:1: Type 'NEM' does not conform to protocol 'TargetType'
/Users/yauhenishauchenka/Desktop/sources/projects/NEMiOSApp/NEMWallet/Application/Networking/NemAPI.swift:83:21: Type 'Task' has no member 'requestParameters'
/Users/yauhenishauchenka/Desktop/sources/projects/NEMiOSApp/NEMWallet/Application/Networking/NemAPI.swift:85:21: Type 'Task' has no member 'requestParameters'
/Users/yauhenishauchenka/Desktop/sources/projects/NEMiOSApp/NEMWallet/Application/Networking/NemAPI.swift:87:21: Type 'Task' has no member 'requestParameters'
/Users/yauhenishauchenka/Desktop/sources/projects/NEMiOSApp/NEMWallet/Application/Networking/NemAPI.swift:89:21: Type 'Task' has no member 'requestPlain'
```

https://monosnap.com/file/1NZuW4zQSGE9wh4DD7iIZqkurQ7j0N

@thomasoehri

**Comment by thomasoehri** [comment] 2018-01-29 14:12
This was caused by an outdated version of the dependency Moya.
I've updated the dependency to the latest version and committed the modified Cartfile to the develop branch. 

Update all dependencies again using Carthage (carthage update --platform iOS --no-use-binaries) and after it should build fine.

**Closed** 2018-02-15 10:47 UTC
